setwd("D:\\Proyecto")
datos = read.csv("Datos.csv", header = T, sep = ";")
bartlett.test(LL_zacc_std~Actividad, data=datos)
attach(datos)
bartlett.test(RL_xacc_mean, Actividad)
bartlett.test(RL_xacc_mean~Actividad)
library(lawstat)
levene.test(LL_zacc_mean,Actividad)
fligner.test(RL_xacc_mean~Actividad, datos)
library(outliers)
cochran.test(RL_xacc_mean~Actividad)
shapiro.test(RL_xacc_mean)
t.test(RL_xacc_mean)