setwd("D:\\Proyecto")
datos = read.csv("Datos.csv", header = T, sep = ";")
attach(datos)
require(nortest)
library(moments)
library(fpp)
qqnorm(variable)
qqline(variable)
jarque.bera.test(variable)
ad.test(variable)
lillie.test(variable)
summary(variable)
x=variable+min
summary(x)
lambda <- BoxCox.lambda(x, method=c("loglik"), lower =-5, upper=5)
lambda
w<-BoxCox(x,lambda)
jarque.bera.test(w)
ad.test(variable)
lillie.test(variable)
qqnorm(w)
qqline(w)
